# Generated by Django 4.2.7 on 2023-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0004_utilisateur_emprunt_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_debut_emprunt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_fin_emprunt',
            field=models.DateField(null=True),
        ),
    ]
