# Generated by Django 4.2.7 on 2024-01-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0005_alter_emprunt_date_debut_emprunt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField()),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiel.materiel')),
            ],
        ),
    ]
