# Generated by Django 4.2.7 on 2024-01-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0007_commentaire_auteur_commentaire_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='materiel.utilisateur'),
        ),
    ]
