# Generated by Django 4.2.7 on 2024-02-20 15:23

from django.db import migrations

def creer_groupes(apps, schema_migration):
    Utilisateur = apps.get_model('materiel', 'Utilisateur')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_emplacement, created = Permission.objects.get_or_create(codename='add_emplacement')
    change_emplacement, created = Permission.objects.get_or_create(codename='change_emplacement')
    delete_emplacement, created = Permission.objects.get_or_create(codename='delete_emplacement')
    view_emplacement, created = Permission.objects.get_or_create(codename='view_emplacement')

    add_categorie, created = Permission.objects.get_or_create(codename='add_categorie')
    change_categorie, created = Permission.objects.get_or_create(codename='change_categorie')
    delete_categorie, created = Permission.objects.get_or_create(codename='delete_categorie')
    view_categorie, created = Permission.objects.get_or_create(codename='view_categorie')

    add_materiel, created = Permission.objects.get_or_create(codename='add_materiel')
    change_materiel, created = Permission.objects.get_or_create(codename='change_materiel')
    delete_materiel, created = Permission.objects.get_or_create(codename='delete_materiel')
    view_materiel, created = Permission.objects.get_or_create(codename='view_materiel')

    add_utilisateur, created = Permission.objects.get_or_create(codename='add_utilisateur')
    change_utilisateur, created = Permission.objects.get_or_create(codename='change_utilisateur')
    delete_utilisateur, created = Permission.objects.get_or_create(codename='delete_utilisateur')
    view_utilisateur, created = Permission.objects.get_or_create(codename='view_utilisateur')

    add_emprunt, created = Permission.objects.get_or_create(codename='add_emprunt')
    change_emprunt, created = Permission.objects.get_or_create(codename='change_emprunt')
    delete_emprunt, created = Permission.objects.get_or_create(codename='delete_emprunt')
    view_emprunt, created = Permission.objects.get_or_create(codename='view_emprunt')

    add_commentaire, created = Permission.objects.get_or_create(codename='add_commentaire')
    change_commentaire, created = Permission.objects.get_or_create(codename='change_commentaire')
    delete_commentaire, created = Permission.objects.get_or_create(codename='delete_commentaire')
    view_commentaire, created = Permission.objects.get_or_create(codename='view_commentaire')
    
    usager_permissions = [
        view_emplacement,
        view_categorie,
        view_materiel,
        change_utilisateur,
        view_utilisateur,
        change_emprunt,
        view_emprunt,
        add_commentaire,
        change_commentaire,
        delete_commentaire,
        view_commentaire,
    ]

    emprunteur_permissions = [
        add_emprunt,
    ]

    moderateur_permissions = [
        add_emplacement,
        change_emplacement,
        delete_emplacement,
        add_categorie,
        change_categorie,
        delete_categorie,
        add_materiel,
        change_materiel,
        delete_materiel,
        add_utilisateur,
        delete_utilisateur,
        delete_emprunt,
    ]
    
    usagers = Group(name='usagers')
    usagers.save()    
    usagers.permissions.set(usager_permissions)

    emprunteurs = Group(name='emprunteurs')
    emprunteurs.save()    
    emprunteurs.permissions.set(emprunteur_permissions)

    moderateurs = Group(name='moderateurs')
    moderateurs.save()    
    moderateurs.permissions.set(moderateur_permissions)

    # à modifier ouais ouais
    for utilisateur in Utilisateur.objects.all():
        usagers.user_set.add(utilisateur.user)

        if utilisateur.peut_emprunter:
            emprunteurs.user_set.add(utilisateur.user)

        if utilisateur.est_moderateur:
            moderateurs.user_set.add(utilisateur.user)


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0008_alter_commentaire_auteur'),
    ]

    operations = [
        migrations.RunPython(creer_groupes)
    ]
