# Generated by Django 4.2.7 on 2023-11-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prefixe_identifiant', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('commune', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('identifiant', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('empruntable', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='materiel.categorie')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='materiel.emplacement')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_resa', models.DateField()),
                ('date_fin_resa', models.DateField()),
                ('date_debut_emprunt', models.DateField()),
                ('date_fin_emprunt', models.DateField()),
                ('cloture', models.BooleanField(default=False)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiel.materiel')),
            ],
        ),
    ]
