# Generated by Django 4.2.7 on 2023-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0002_alter_materiel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
